baseURL = "https://faq.teipublisher.com/"
languageCode = "en-us"
title = "TEI Publisher FAQ"
theme = "learn"

[params]
    themeVariant = "teipublisher"
    siteLandingPage = "https://teipublisher.com"
    landingPageName = "<i class='fas fa-home'></i> Frequently Asked Questions"
    editURL = "https://github.com/eeditiones/tei-publisher-faq/edit/master/content/"
[[menu.shortcuts]]
    name = "<i class='fas fa-tags'></i> Tags"
    url = "/tags"
    weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON"]
